[package]
name = "rustcompressor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

colored = "2.0.4"
flate2 = "1.0.28"